### ISSUE TITLE
Error in UseMethod("predict") :

### ISSUE THREAD

**Issue by Mahnaz2019** [haddocking/iSee#1] opened 2021-12-01 17:02 UTC
Dear iSee team,

I would like to use iSee for my PhD research but I faced an error that I need help with it.  I downloaded the latest R and Rainforest library. 

Please see below. Thank you. 
Mahnaz

(base) mahnaz@M iSee-master % Rscript run_iSEE.R features_examples.tsv

Warning: namespace ‘caret’ is not available and has been replaced
by .GlobalEnv when processing object ‘model’
Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "c('train', 'train.formula')"
Calls: predict
Execution halted

**Comment by CunliangGeng** [comment] 2021-12-02 09:38
Hi Mahnaz, thanks for using iSEE. 

I reproduced your problem on my machine. The cause is that package "[caret](https://cran.r-project.org/web/packages/caret/)" is not installed.
So you can run command `install.packages("caret")` in R to install it, then iSEE should work.

I will update README to include "caret" as a requirement.
Thanks for your feedback, let me know if you have further questions.

**Comment by Mahnaz2019** [comment] 2021-12-03 08:13
Dear Cunliang,

Thank you for the advice. I installed caret and it now works.

Best,
Mahnaz
________________________________

**Comment by CunliangGeng** [comment] 2021-12-03 08:40
Great! I'm closing the issue then.

**Closed as completed by CunliangGeng** 2021-12-03 08:40 UTC
